service:
  name: dynamic-dns

plugins:
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
  stage: prod
  memorySize: 128

functions:
  setRecord:
    handler: index.handler
    environment: ${file(env.yml)}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - route53:ChangeResourceRecordSets
        Resource: arn:aws:route53:::hostedzone/*
    events:
      - http:
          path: /
          method: post
          cors: true